import Head from "next/head";

export default function HeadComponent() {
  return (
    <Head>
      <title>Taksa</title>

      <meta content="width=device-width, initial-scale=1" name="viewport" />

      <meta name="description" content="Generated by create next app" />

      {/*<link rel="icon" href="/favicon-32x32.svg" />*/}

      {/*<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />*/}

      {/*<link rel="icon shortcut" type="image/x-icon" href="/favicon-32x32.ico" />*/}

      {/*<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />*/}

      {/*<link rel="apple-touch-icon" sizes="180x180" href="/favicon-180x180.png" />*/}
    </Head>
  );
}
